Repository ork-a/pan_kanapka, pull requests merged in 2019-05, with the labels that each got.

#10 Users & groups.
  PanKanapka/PanKanapka/settings.py
  PanKanapka/PanKanapka/urls.py
  PanKanapka/clients/__init__.py
  PanKanapka/clients/admin.py
  PanKanapka/clients/apps.py
  PanKanapka/clients/forms.py
  PanKanapka/clients/migrations/0001_initial.py
  PanKanapka/clients/migrations/__init__.py
  PanKanapka/clients/models.py
  PanKanapka/clients/tests.py
  PanKanapka/clients/urls.py
  PanKanapka/clients/views.py
  PanKanapka/db.sqlite3
Labels: good first issue

#21 Pan bulka 120519
  PanKanapka/PanKanapka/media/kanapki/images/wiki_tomato_test.jpg
  PanKanapka/PanKanapka/settings.py
  PanKanapka/PanKanapka/urls.py
  PanKanapka/bulka/models.py
Labels: nowa funkcjonalność

#22 New app/orders
  .gitignore
  .idea/PanKanapka.iml
  PanKanapka/PanKanapka/media/kanapki/images/wiki_tomato_test.jpg
  PanKanapka/PanKanapka/settings.py
  PanKanapka/PanKanapka/urls.py
  PanKanapka/bulka/admin.py
  PanKanapka/bulka/apps.py
  PanKanapka/bulka/migrations/0001_initial.py
  PanKanapka/bulka/migrations/0002_skladnikialergeny.py
  PanKanapka/bulka/migrations/0003_kanapkiskladniki.py
  PanKanapka/bulka/migrations/0004_auto_20190501_1943.py
  PanKanapka/bulka/migrations/0005_auto_20190501_2007.py
  PanKanapka/bulka/migrations/0006_kanapki_kan_nazwa.py
  PanKanapka/bulka/models.py
  PanKanapka/bulka/views.py
  PanKanapka/clients/admin.py
  PanKanapka/clients/forms.py
  PanKanapka/clients/migrations/0001_initial.py
  PanKanapka/clients/models.py
  PanKanapka/clients/templates/registration/login.html
  PanKanapka/clients/urls.py
  PanKanapka/clients/views.py
  PanKanapka/db.sqlite3
  PanKanapka/manage.py
  PanKanapka/orders/__init__.py
  PanKanapka/orders/admin.py
  PanKanapka/orders/apps.py
  PanKanapka/orders/migrations/0001_initial.py
  PanKanapka/orders/migrations/0002_auto_20190518_1532.py
  PanKanapka/orders/migrations/0003_auto_20190518_1533.py
  PanKanapka/orders/migrations/0004_ordersandwiches_user.py
  PanKanapka/orders/migrations/__init__.py
  PanKanapka/orders/models.py
  PanKanapka/orders/templates/summary_company.html
  PanKanapka/orders/templates/summary_user.html
  PanKanapka/orders/tests.py
  PanKanapka/orders/urls.py
  PanKanapka/orders/views.py
  PanKanapka/sandwiches/__init__.py
  PanKanapka/sandwiches/admin.py
  PanKanapka/sandwiches/apps.py
  PanKanapka/sandwiches/management/__init__.py
  PanKanapka/sandwiches/management/commands/__init__.py
  PanKanapka/sandwiches/management/commands/populate.py
  PanKanapka/sandwiches/media/sandwiches/images/s1.jpg
  PanKanapka/sandwiches/media/sandwiches/images/s2.jpg
  PanKanapka/sandwiches/media/sandwiches/images/s3.jpeg
  PanKanapka/sandwiches/media/sandwiches/images/s4.jpeg
  PanKanapka/sandwiches/media/sandwiches/images/s5.jpg
  PanKanapka/sandwiches/migrations/0001_initial.py
  PanKanapka/sandwiches/migrations/0002_auto_20190518_1201.py
  PanKanapka/sandwiches/migrations/__init__.py
  PanKanapka/sandwiches/models.py
  PanKanapka/sandwiches/templates/sandwiches_list.html
  PanKanapka/sandwiches/tests.py
  PanKanapka/sandwiches/urls.py
  PanKanapka/sandwiches/views.py
  PanKanapka/templates/base.html
  PanKanapka/templates/messages.html
Labels: nowa funkcjonalność

#24 Populate databases using content from csv files
  .idea/PanKanapka.iml
  .idea/misc.xml
  .idea/vcs.xml
  PanKanapka/PanKanapka/settings.py
  PanKanapka/doc/demo_data_in_csv/allergens.csv
  PanKanapka/doc/demo_data_in_csv/clients.csv
  PanKanapka/doc/demo_data_in_csv/companies.csv
  PanKanapka/doc/demo_data_in_csv/ingredients.csv
  PanKanapka/doc/demo_data_in_csv/sandwiches.csv
  PanKanapka/sandwiches/media/sandwiches/images/s1.jpg
  PanKanapka/sandwiches/media/sandwiches/images/s2.jpg
  PanKanapka/sandwiches/media/sandwiches/images/s3.jpeg
  PanKanapka/sandwiches/media/sandwiches/images/s4.jpeg
  PanKanapka/sandwiches/media/sandwiches/images/s5.jpg
  PanKanapka/sandwiches/migrations/__init__.py
  PanKanapka/tools/__init__.py
  PanKanapka/tools/admin.py
  PanKanapka/tools/apps.py
  PanKanapka/tools/csv2db.py
  PanKanapka/tools/management/commands/cleandb.py
  PanKanapka/tools/management/commands/filldb.py
  PanKanapka/tools/migrations/__init__.py
  PanKanapka/tools/models.py
  PanKanapka/tools/tests.py
  PanKanapka/tools/urls.py
  PanKanapka/tools/views.py
Labels: dane projektowe, nowa funkcjonalność

#32 Modyfikacja zamówienia.
  PanKanapka/PanKanapka/settings.py
  PanKanapka/orders/admin.py
  PanKanapka/orders/models.py
  PanKanapka/orders/templates/summary_user.html
  PanKanapka/orders/urls.py
  PanKanapka/orders/views.py
Labels: nowa funkcjonalność

#38 Złożone zamówienia.
  PanKanapka/orders/templates/placed_orders.html
  PanKanapka/orders/urls.py
  PanKanapka/orders/views.py
Labels: nowa funkcjonalność
